# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 21:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('skill', models.CharField(max_length=256)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Critic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user_id', models.IntegerField()),
                ('to_user_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('user_credits', models.IntegerField()),
                ('created_on', models.DateTimeField()),
                ('skills', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
