# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.CharField(max_length=36)),
                ('followee_id', models.CharField(max_length=36)),
                ('followee_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='contenttypes.ContentType')),
                ('follower_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='contenttypes.ContentType')),
            ],
        ),
    ]
