# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 16:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('aggregate_id', models.UUIDField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('stream', models.CharField(max_length=255)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
                ('committed', models.BooleanField(default=False)),
            ],
        ),
    ]
