# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 12:13
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_profile', '0002_auto_20160826_1213'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('role', models.CharField(blank=True, max_length=128)),
                ('last_update', models.DateField(blank=True, default=datetime.date.today)),
                ('compensation', models.CharField(max_length=128)),
                ('kind', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('C', 'Contract'), ('FL', 'Freelance'), ('R', 'Remote')], default='FT', max_length=2)),
                ('slug', models.SlugField(blank=True, default='', max_length=70, null=True, unique=True, verbose_name='Slug')),
                ('attitude', models.FloatField(default=1.5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(2.0)])),
                ('consciousness', models.FloatField(default=3.5, validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(5.0)])),
                ('openness', models.FloatField(default=3.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('decision_making', models.FloatField(default=1.5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(2.0)])),
                ('agreeableness', models.FloatField(default=2.5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(4.0)])),
                ('emotional_stability', models.FloatField(default=2.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(3.0)])),
                ('organizing', models.FloatField(default=2.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(3.0)])),
                ('reasoning', models.FloatField(default=3.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('creativity', models.FloatField(default=3.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('critical_thinking', models.FloatField(default=3.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('skills', models.ManyToManyField(blank=True, to='account_profile.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account_profile.Profile')),
            ],
        ),
    ]
