version: '2'

services:
  app:
    build: ./docker/app/
    volumes:
      - '.:/app'
      - 'logs:/var/logs/meanwise'
    links:
      - postgres
      - redis
    ports:
      - '8000:8000'

  postgres:
    build: ./docker/postgres/
    environment:
      POSTGRES_USER: 'meanwise'
      POSTGRES_PASSWORD: 'meanwise1!'
    volumes:
      - 'postgres:/var/lib/postgres/data'
  redis:
    image: redis:latest

volumes:
  postgres: ~
  logs: ~