version: '2'

services:
  app:
    build: ./docker/app/
    volumes:
      - '.:/app'
      - 'logs:/var/logs/meanwise'
      - 'media:/app/media'
      - 'static:/app/static'
      - 'whoosh:/whoosh'
    links:
      - postgres
      - elasticsearch
      - nginx
    ports:
      - '8000:8000'
    environment:
      ELK_LOGSTASH_HOST: '192.168.22.131'
      ELK_LOGSTASH_PORT: '12201'
      STATIC_URL: 'http://localhost:8001/static/'

  nginx:
    image: nginx:1.12.0
    ports:
      - 8001:80
    volumes:
      - media:/usr/share/nginx/html/media
      - static:/usr/share/nginx/html/static
      - ./docs/dev-docs/build/html:/usr/share/nginx/html/docs

  cron:
    build: ./docker/cron/
    volumes:
      - '.:/app'
      - 'media:/app/media'
      - 'static:/app/static'
      - 'whoosh:/whoosh'
    links:
      - postgres
      - elasticsearch
    environment:
      ELK_LOGSTASH_HOST: '192.168.22.131'
      ELK_LOGSTASH_PORT: '12201'

  postgres:
    build: ./docker/postgres/
    environment:
      POSTGRES_USER: 'meanwise'
      POSTGRES_PASSWORD: 'meanwise1!'
    volumes:
      - 'postgres:/var/lib/postgres/data'
  redis:
    image: redis:latest
  elasticsearch:
    image: elasticsearch:2.3
    ports:
      - '9210:9200'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data

volumes:
  postgres: ~
  logs: ~
  esdata1: ~
  media: ~
  static: ~
  whoosh: ~
