version: '2'

services:
  app:
    build: ./docker/app/
    volumes:
      - '.:/app'
      - 'logs:/var/logs/meanwise'
    links:
      - postgres
      - redis
    ports:
      - '8000:8000'

  postgres:
    build: ./docker/postgres/
    environment:
      POSTGRES_USER: 'meanwise'
      POSTGRES_PASSWORD: 'meanwise1!'
    volumes:
      - 'postgres:/var/lib/postgres/data'
  redis:
    image: redis:latest
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    ports:
      - '9200:9200'
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data

volumes:
  postgres: ~
  logs: ~
  esdata1: ~