# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 16:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('logo', models.ImageField(upload_to='brand_logos')),
                ('logo_thumbnail', models.ImageField(upload_to='brand_thumbnails')),
                ('profile_image', models.ImageField(null=True, upload_to='brand_profiles')),
                ('profile_color', models.CharField(default='#000000', max_length=7)),
                ('description', models.CharField(max_length=500)),
                ('compact_display_image', models.ImageField(upload_to='brand_compact_display')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_update_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrandMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='members', to='brands.Brand')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
