# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_auto_20170928_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
