# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 18:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20170423_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resolution',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'height': 1920, 'width': 1080}),
            preserve_default=False,
        ),
    ]
