# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 09:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='resolution',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
