# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 20:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0005_auto_20170622_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='mentioned_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
