# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_comment_comment_mentioned_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_mentioned_users',
            new_name='mentioned_users',
        ),
    ]
