# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-14 15:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0007_comment_comment_mentioned_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_mentioned_users',
        ),
        migrations.AddField(
            model_name='comment',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='comment_mentioned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='geo_location_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='geo_location_lng',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
