# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20170731_1432'),
        ('post', '0008_auto_20170802_1433'),
    ]

    operations = [
    ]
