# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20170921_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post_audio_thumbnails'),
        ),
        migrations.AddField(
            model_name='post',
            name='pdf_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post_pdf_thumbnails'),
        ),
    ]
