# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('post', '0009_auto_20170924_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='posts', to='brands.Brand'),
        ),
    ]
