# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 14:48
from __future__ import unicode_literals

from django.db import migrations, models

import django.contrib.postgres.fields.jsonb


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_post_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='post_audio'),
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='post_pdf'),
        ),
        migrations.AddField(
            model_name='post',
            name='link_meta_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='audio_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post_audio_thumbnails'),
        ),
        migrations.AddField(
            model_name='post',
            name='pdf_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post_pdf_thumbnails'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF'), ('audio', 'Audio'), ('text', 'Text'), ('link', 'Link')], default=None, max_length=5, null=True),
        ),
    ]
