# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20170925_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF'), ('audio', 'Audio'), ('text', 'Text'), ('link', 'Link')], default=None, max_length=5),
        ),
    ]
