# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 23:07
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Q

from post.models import Post


def add_post_type(apps, scheme_editor):
    Posts = apps.get_model("post", "Post")
    post_image = Posts.objects.filter(~Q(image='') & ~Q(image=None))
    post_video = Posts.objects.filter(~Q(video='') & ~Q(video=None))
    post_link = Posts.objects.filter(~Q(link='') & ~Q(link=None))
    post_pdf = Posts.objects.filter(~Q(pdf='') & ~Q(pdf=None))
    post_audio = Posts.objects.filter(~Q(audio='') & ~Q(audio=None))
    post_text = Posts.objects.filter(
        (~Q(text='') & ~Q(text=None)) &
        (Q(image='') | Q(image=None)) &
        (Q(video='') | Q(video=None)) &
        (Q(link='') | Q(link=None)) &
        (Q(pdf='') | Q(pdf=None)) &
        (Q(audio='') | Q(audio=None))
    )

    post_image.update(post_type=Post.TYPE_IMAGE)
    post_video.update(post_type=Post.TYPE_VIDEO)
    post_audio.update(post_type=Post.TYPE_AUDIO)
    post_link.update(post_type=Post.TYPE_LINK)
    post_pdf.update(post_type=Post.TYPE_PDF)
    post_text.update(post_type=Post.TYPE_TEXT)


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_post_post_type'),
    ]

    operations = [
        migrations.RunPython(add_post_type),
    ]
