# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 23:07
from __future__ import unicode_literals

from django.db import migrations
from post.models import Post


def add_post_type(apps, scheme_editor):
    Posts = apps.get_model("post", "Post")
    post_image = Posts.objects.filter(image__isnull=False)
    post_video = Posts.objects.filter(video__isnull=False)
    post_link = Posts.objects.filter(link__isnull=False)
    post_pdf = Posts.objects.filter(pdf__isnull=False)
    post_audio = Posts.objects.filter(audio__isnull=False)
    post_text = Posts.objects.filter(
        text__isnull=False,
        image__isnull=True,
        video__isnull=True,
        link__isnull=True,
        pdf__isnull=True,
        audio__isnull=True)

    post_image.update(post_type=Post.TYPE_IMAGE)
    post_video.update(post_type=Post.TYPE_VIDEO)
    post_audio.update(post_type=Post.TYPE_AUDIO)
    post_link.update(post_type=Post.TYPE_LINK)
    post_pdf.update(post_type=Post.TYPE_PDF)
    post_text.update(post_type=Post.TYPE_TEXT)


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_post_post_type'),
    ]

    operations = [
        migrations.RunPython(add_post_type),
    ]
