# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_add_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='brands.Brand'),
        ),
    ]
