# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-08 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20170928_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='panaroma_type',
            field=models.CharField(choices=[('equirectangular', 'Equirectangular')], default=None, max_length=15, null=True),
        ),
    ]
