# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-21 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_post_panaroma_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_work',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='panaroma_type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('equirectangular', 'Equirectangular')], default=None, max_length=15, null=True),
        ),
    ]
