# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 17:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0017_auto_20171115_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_with', jsonfield.fields.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='allow_sharing',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='visible_to',
            field=models.CharField(choices=[('Public', 'Public'), ('Friends', 'Friends'), ('List', 'List')], default='Public', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='share_list_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.ShareList'),
        ),
    ]
