# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        ('post', '0020_usertopic_is_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='college.College'),
        ),
    ]
