# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_post_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='interest',
        ),
    ]
