# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_post_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Interest'),
        ),
    ]
