# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertopic',
            name='interest',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
