# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 13:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


def add_uuid(apps, schema_editor):
    Post = apps.get_model('post', 'Post')
    for post in Post.objects.filter(post_uuid__isnull=True):
        post.post_uuid = uuid.uuid4()
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0028_create_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_ids',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='allow_sharing',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(add_uuid, reverse_code=migrations.RunPython.noop),
    ]
