# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 09:09
from __future__ import unicode_literals

from django.db import migrations

from post.models import Post


def add_media_ids(apps, schema_editor):
    for post in Post.objects.all():
        post_type = post.get_post_type()
        if post.media_ids is not None and len(post.media_ids) > 0:
            continue
        if post_type == Post.TYPE_IMAGE:
            post.media_ids = [{
                'media_id': post.image.name,
                'type': 'image'
            }]
        elif post_type == Post.TYPE_VIDEO:
            post.media_ids = [{
                'media_id': post.video.name,
                'type': 'video'
            }]
        else:
            continue

        post.save()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('post', '0031_auto_20180227_1442'),
    ]

    operations = [
        migrations.RunPython(add_media_ids, migrations.RunPython.noop),
    ]
