# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 07:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0032_auto_add_media_ids_to_old_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_ids',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
