# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('filename', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('storage', models.CharField(max_length=20)),
                ('orphan', models.BooleanField(default=True)),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
