# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 12:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('account_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('searchable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('code', models.CharField(max_length=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('searchable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ac', 'Academic'), ('ah', 'Achievement'), ('ev', 'Event'), ('pj', 'Project'), ('pf', 'Professional'), ('ot', 'Other')], max_length=2)),
                ('start_day', models.PositiveIntegerField(blank=True, null=True)),
                ('start_month', models.PositiveIntegerField(blank=True, null=True)),
                ('start_year', models.PositiveIntegerField(blank=True, null=True)),
                ('end_day', models.PositiveIntegerField(blank=True, null=True)),
                ('end_month', models.PositiveIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('ongoing', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=1024)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.City')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_profile.Profile')),
            ],
        ),
    ]
