# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seenpost',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
