# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20170726_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seenpostbatch',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
