# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128)),
                ('area', models.CharField(blank=True, default='', max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('place_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=270, unique=True)),
                ('searchable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('city', models.CharField(blank=True, default='', max_length=64)),
                ('area', models.CharField(blank=True, default='', max_length=128)),
                ('country', models.CharField(default='', max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('place_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=270, unique=True)),
                ('searchable', models.BooleanField(default=True)),
            ],
        ),
    ]
