# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import enum_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_string', models.CharField(max_length=10)),
                ('version_sort', models.CharField(max_length=10)),
                ('status', models.IntegerField(choices=[(-1, 'Inactive'), (0, 'Draft'), (1, 'Published')], default=0)),
                ('platform', enum_field.EnumField(enum_field.Enum(('ios', 'iOS'), ('android', 'Android')))),
            ],
        ),
    ]
