# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appversion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('last_changed_date', models.DateTimeField(auto_now=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appversion.Version')),
            ],
        ),
    ]
