# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20170411_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitegroup',
            name='max_invites',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo_thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='profile_photo_thumbs'),
        ),
    ]
