# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-18 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20170612_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profession_text',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
