# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-18 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_userprofile_skills_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_background_color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.IntegerField(default=0),
        ),
    ]
