# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20170618_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='interest_photos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to='cover_photos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profile_photos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo_thumbnail',
            field=models.ImageField(blank=True, upload_to='profile_photo_thumbs'),
        ),
    ]
