# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-05 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0009_auto_20170620_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterestRelevance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_views', models.IntegerField()),
                ('old_views', models.IntegerField()),
                ('last_reset', models.DateTimeField()),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Interest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
