# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 16:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0010_userinterestrelevance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Friend_request_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Friend_request_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Friend Request',
                'verbose_name_plural': 'Friend Requests',
            },
        ),
        migrations.AlterModelOptions(
            name='userfriend',
            options={'verbose_name': 'Friend', 'verbose_name_plural': 'Friends'},
        ),
        migrations.RemoveField(
            model_name='userfriend',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='userfriend',
            name='status',
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set([('user', 'friend')]),
        ),
    ]
