# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_auto_20170830_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfriend',
            name='status',
            field=models.CharField(blank=True, choices=[('PE', 'Pending'), ('AC', 'Accepted'), ('RE', 'Rejected')], default=None, max_length=2),
        ),
    ]
