# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 08:07
from __future__ import unicode_literals

from django.db import migrations


def import_data(apps, schema_editor):
    UserFriend = apps.get_model("userprofile", "UserFriend")
    friend_list = UserFriend.objects.filter(status='PE')

    FriendRequest = apps.get_model("userprofile", "FriendRequest")

    for friend in friend_list:
        FriendRequest.objects.create(
            user=friend.user,
            friend=friend.friend
        )
        friend.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_auto_20170910_0807'),
    ]

    operations = [
        migrations.RunPython(import_data),
    ]
