# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_auto_20170910_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriend',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
