# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_userfriend_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='post_boost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
