# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_userprofile_post_boost'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
