# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 12:13
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Company Name')),
                ('slug', models.SlugField(blank=True, default='', max_length=70, null=True, unique=True, verbose_name='Slug')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyCulture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influence', models.IntegerField(choices=[(3, 'Challenges authority, likes to be empowered'), (2, 'Neutral'), (1, 'Respect for heirachial structure')], default=2)),
                ('adventurous', models.IntegerField(choices=[(3, 'Adventurous, risk-taking'), (2, 'Neutral'), (1, 'Rigorous, cautious')], default=2)),
                ('achievement', models.IntegerField(choices=[(3, 'Achievement striving, active'), (2, 'Neutral'), (1, 'Follower, comtemplative, less concerned with high achievement')], default=2)),
                ('col_ind', models.IntegerField(choices=[(3, 'Collectivist, Doing for others'), (2, 'Neutral'), (1, 'Independent, Little trust')], default=2)),
                ('openness', models.IntegerField(choices=[(3, 'Liberal, open to future experience'), (2, 'Neutral'), (1, 'Conservative, stability, tradition')], default=2)),
                ('pub_vs_priv', models.IntegerField(choices=[(3, 'Friendly, seeking company'), (2, 'Neutral'), (3, 'Reservered, needs privacy')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('isHQ', models.BooleanField(default=False)),
                ('lon', models.DecimalField(decimal_places=3, max_digits=8)),
                ('lat', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('company_description', models.CharField(max_length=512, null=True, verbose_name='Company Description')),
                ('company_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Company Size')),
                ('company_email', models.CharField(max_length=128)),
                ('industry', models.CharField(max_length=128)),
                ('date_founded', models.DateField(default=datetime.date.today)),
                ('company_type', models.CharField(max_length=128)),
                ('company_vision', models.TextField()),
                ('growth_plans', models.CharField(choices=[('50%', 'Extreme Growth (Over 50% over this year)'), ('15-25%', 'Significant Growth (15-25% over this year)'), ('NA', "I don't know")], db_index=True, default='NA', max_length=10, null=True)),
                ('culture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.CompanyCulture')),
                ('offices', models.ManyToManyField(blank=True, to='company.CompanyLocation')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='EmailConfirmation',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='company.Company', verbose_name='Company Name')),
                ('email', models.EmailField(db_index=True, max_length=128, unique=True, verbose_name='Email')),
                ('token', models.CharField(max_length=256, unique=True, verbose_name='Token')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmed')),
            ],
        ),
    ]
