# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 18:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotifications', '0002_post_comment_mentioned_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='comment_mentioned_users',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='post_mentioned_users',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
