# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-20 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotifications', '0004_auto_20170814_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='profile_photo_thumbnail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
