# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('visual_check_image', models.CharField(max_length=255)),
                ('profile_created', models.BooleanField(default=False)),
                ('probability', models.FloatField()),
                ('match', models.BooleanField()),
                ('match_id', models.UUIDField(null=True)),
                ('audio_captcha_sentence', models.CharField(default=None, max_length=100, null=True)),
                ('audio_captcha_result', models.NullBooleanField(default=None)),
                ('user_verification_video', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
