# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='face_id',
            field=models.UUIDField(null=True),
        ),
    ]
