# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 12:13
from __future__ import unicode_literals

import common.cache
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=140)),
                ('description', models.CharField(blank=True, default='', max_length=1024)),
                ('order', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None)),
                ('state', models.CharField(choices=[('df', 'Draft'), ('pb', 'Published'), ('dl', 'Deleted')], default='df', max_length=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('searchable', models.BooleanField(default=True)),
                ('cover_photo', models.URLField(blank=True, default='')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_profile.Profile')),
                ('skills', models.ManyToManyField(to='account_profile.Skill')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, common.cache.SerializerCached),
        ),
        migrations.CreateModel(
            name='Workitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=1024)),
                ('type', models.CharField(choices=[('img', 'Image'), ('you', 'Youtube'), ('vim', 'Vimeo'), ('scl', 'Sound Cloud'), ('spo', 'Spotify'), ('gis', 'Gist'), ('jsf', 'JSFiddle')], max_length=3)),
                ('link', models.CharField(max_length=1024)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workitems', to='works.Work')),
            ],
        ),
    ]
